Added "user" label
MindFlavor/prometheus_folder_size_exporter pull request #1
Opened 2020-08-11 22:48 UTC by scatenag

In order to monitor folders size by users,
I added the "user" label.

-----------

I appreciated very much your exporter.

Actually, in more general terms, 
It would be useful to allow more and arbitrary labels to be expressed in the configuration file 
and then reported, as is, by the exporter.

Unfortunately, I am new to Rust and, for the moment, I am not able to do so;
thus I modified only for my need, that is, to have a "user" label.

2020-08-17 11:18 UTC, MindFlavor requested changes
Thank you for your contribution! Please just revert the changes in the repo location and I will merge it gladly!

2020-08-17 11:18 UTC, MindFlavor commented on src/folder_scanner.rs
> +    pub(crate) user: String,
This could be made optional. Will fix in a following PR.

2020-08-17 11:18 UTC, MindFlavor commented on Cargo.toml
> +repository     = "https://github.com/scatenag/prometheus_folder_size_exporter"
It's ok to add yourself as coauthor but it's not to hijack the repo. Please revert these changes.

2020-08-19 07:45 UTC, scatenag commented
I reverted the repo hijack (sorry about that, I was not careful).
Thanks.

---------------------

Ps: 
If you make `user` optional in a future PR...
I suggest you to consider adding the ability to express arbitrary additional labels.

I imagine  something like that:
`{ "path": "/home/mindflavor/.cargo", "recursive": false , "additional_labels":  "WHATHEVER"}`
resulting in something like
`folder_size{path="/home/mindflavor/.cargo",recursive="false", WHATHEVER} 4297494128`

In such a way one can define arbitrary additional labels (as user, user group etc) and use in its monitoring dashboards.

What do you thing about it ?

2020-08-25 07:34 UTC, MindFlavor commented
Thank you!

2020-08-25 07:34 UTC, merged